<table>
    <thead>
    <tr>
        <th>Name</th>
        <th>Email</th>
    </tr>
    </thead>
    <tbody>
        <tr>
            <td>teste</td>
            <td>fodase</td>
        </tr>
    </tbody>
</table>
